/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.com.events.presentation;

import co.com.events.domain.entities.Category;
import co.com.events.domain.entities.Evento;
import co.com.events.domain.entities.Rol;
import co.com.events.domain.entities.Usuario;
import co.com.events.service.CategoryService;
import co.com.events.service.EventService;
import co.com.events.service.RolService;
import co.com.events.service.UsuarioService;

import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Libardo Pantoja, Julio A. Hurtado
 */
public class GUIUsuariosFind extends javax.swing.JDialog {
    private UsuarioService usuarioService;
    private RolService rolService;
    /**
     * Creates new form GUIProductsFind
     */
    public GUIUsuariosFind(java.awt.Frame parent, boolean modal,UsuarioService usuarioService, RolService rolService) {
        super(parent, modal);
        initComponents();
        initializeTable();
        this.rolService = rolService;
        this.usuarioService = usuarioService;
        setLocationRelativeTo(null); //centrar al ventana
    }
    
    private void initializeTable() {
        tblCategories.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Id", "Usuario", "Correo", "Contraseña", "Rol"
                }
        ));
    }
    
        private void fillTable(List<Usuario> listUsuarios) {
        initializeTable();
        DefaultTableModel model = (DefaultTableModel) tblCategories.getModel();
        
        Object rowData[] = new Object[5];//No columnas
        for (int i = 0; i < listUsuarios.size(); i++) {
            System.out.println("--"+listUsuarios.get(i).getRole());
            rowData[0] = listUsuarios.get(i).getUserId();
            rowData[1] = listUsuarios.get(i).getUsername();  
            rowData[2] = listUsuarios.get(i).getEmail();            
            rowData[3] = listUsuarios.get(i).getPassword();            
            rowData[4] = listUsuarios.get(i).getRole().getRoleName();            

            model.addRow(rowData);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnlCenter = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCategories = new javax.swing.JTable();
        pnlNorth = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rdoId = new javax.swing.JRadioButton();
        rdoName = new javax.swing.JRadioButton();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnSearchAll = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Búsqueda de productos");

        pnlCenter.setLayout(new java.awt.BorderLayout());

        tblCategories.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblCategories);

        pnlCenter.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlCenter, java.awt.BorderLayout.CENTER);

        jLabel1.setText("Buscar por:");
        pnlNorth.add(jLabel1);

        buttonGroup1.add(rdoId);
        rdoId.setSelected(true);
        rdoId.setText("Id");
        pnlNorth.add(rdoId);

        buttonGroup1.add(rdoName);
        rdoName.setText("Nombre categoria");
        rdoName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoNameActionPerformed(evt);
            }
        });
        pnlNorth.add(rdoName);

        txtSearch.setPreferredSize(new java.awt.Dimension(62, 32));
        pnlNorth.add(txtSearch);

        btnSearch.setText("Buscar");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        pnlNorth.add(btnSearch);

        btnSearchAll.setText("Buscar Todos");
        btnSearchAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchAllActionPerformed(evt);
            }
        });
        pnlNorth.add(btnSearchAll);

        getContentPane().add(pnlNorth, java.awt.BorderLayout.PAGE_START);

        btnClose.setText("Cerrar");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        jPanel1.add(btnClose);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnSearchAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchAllActionPerformed
        fillTable(usuarioService.findAll());
    }//GEN-LAST:event_btnSearchAllActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
   // TODO add your handling code here:

    // Obtenemos el texto de búsqueda y eliminamos espacios en blanco
    String searchText = txtSearch.getText().trim();

    // Verificamos si se ha seleccionado la opción de búsqueda por ID
    if (rdoId.isSelected()) {
        try {
            // Intentamos convertir el texto de búsqueda a un número Long (ID)
            Long id = Long.parseLong(searchText);
            // Buscamos el usuario por ID usando el servicio de usuarios
            Usuario usuario = usuarioService.findById(id);
            
            if (usuario != null) {
                // Si encontramos el usuario, lo pasamos a la tabla
                fillTable(List.of(usuario));
            } else {
                // Si no encontramos ningún usuario, mostramos un mensaje y una lista vacía
                Messages.showMessageDialog("No hay usuarios con ese ID", "Atención");
                fillTable(List.of());
            }
        } catch (NumberFormatException e) {
            // Si el texto de búsqueda no es un número válido, mostramos una lista vacía
            Messages.showMessageDialog("El ID ingresado no es válido", "Atención");
            fillTable(List.of());
        }
    } 
    // Verificamos si se ha seleccionado la opción de búsqueda por rol
  else if (rdoName.isSelected()) {
    try {
        List<Usuario> usuarios = usuarioService.findByRole(searchText);
        if (!usuarios.isEmpty()) {
            fillTable(usuarios);
        } else {
            Messages.showMessageDialog("No hay usuarios con ese rol", "Atención");
            fillTable(List.of());
        }
    } catch (RuntimeException e) {
        Messages.showMessageDialog(e.getMessage(), "Atención");
        fillTable(List.of());
    }
}
       
    }//GEN-LAST:event_btnSearchActionPerformed
    
    private void rdoNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoNameActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSearchAll;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlCenter;
    private javax.swing.JPanel pnlNorth;
    private javax.swing.JRadioButton rdoId;
    private javax.swing.JRadioButton rdoName;
    private javax.swing.JTable tblCategories;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
